[build]
builder = "dockerfile"

[deploy]
startCommand = "java -jar target/html-translator-0.0.1-SNAPSHOT.jar"
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3

[[build.env]]
name = "SPRING_PROFILES_ACTIVE"
value = "production"