[build]
builder = "dockerfile"

[deploy]
startCommand = "java -jar app.jar"
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3

[build.env]
SPRING_PROFILES_ACTIVE = "production"