services:
  - type: web
    name: globalweb-converter
    env: java
    buildCommand: ./mvnw clean package -DskipTests
    startCommand: java -jar target/html-translator-0.0.1-SNAPSHOT.jar
    plan: free
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: production
      - key: SERVER_PORT
        value: 10000