services:
  - type: web
    name: globalweb-converter
    env: java
    buildCommand: mvn clean package -DskipTests
    startCommand: java -Xmx300m -Dserver.port=$PORT -Dspring.profiles.active=railway -jar target/html-translator-0.0.1-SNAPSHOT.jar
    plan: free
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: railway