server:
  port: ${PORT:8080}
  servlet:
    context-path: /
  error:
    include-message: never
    include-binding-errors: never

spring:
  application:
    name: globalweb-converter
  thymeleaf:
    cache: true
    check-template-location: true
    prefix: classpath:/templates/
    suffix: .html
    encoding: UTF-8
    servlet:
      content-type: text/html
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

logging:
  level:
    com.translator: INFO
    org.springframework.web: WARN
    org.hibernate: WARN
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"

# Translation Configuration
translation:
  provider: mock  # Using mock for free deployment
  batch-size: 100
  max-text-length: 5000
  default-source-language: auto
  default-target-language: en
  mock-fallback: true