server:
  port: ${PORT:8080}
  servlet:
    context-path: /

spring:
  application:
    name: HTML Translator
  
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  
  thymeleaf:
    cache: false
    mode: HTML
    encoding: UTF-8
    servlet:
      content-type: text/html
  
  web:
    resources:
      static-locations: classpath:/static/
      cache:
        period: 3600

# Translation Configuration
translation:
  provider: google  # Options: google, mock
  google-api-key: ${GOOGLE_TRANSLATE_API_KEY:}
  google-credentials-path: ${GOOGLE_CREDENTIALS_PATH:}
  google-project-id: ${GOOGLE_PROJECT_ID:}
  batch-size: 100
  max-text-length: 5000
  default-source-language: auto
  default-target-language: en
  # Fallback to pure algorithmic mock if Google Translate is unavailable
  mock-fallback: true

# Logging Configuration
logging:
  level:
    com.translator: INFO
    org.springframework.web: INFO
    org.springframework.boot: INFO
    org.jsoup: WARN
    root: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: logs/html-translator.log

# Management endpoints
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: when_authorized