server:
  port: ${PORT:8080}
  address: 0.0.0.0
  
# Force Tomcat to bind to all interfaces  
management:
  server:
    address: 0.0.0.0

spring:
  application:
    name: GlobalWeb Converter
  
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  
  thymeleaf:
    cache: false

# Translation Configuration
translation:
  provider: google
  mock-fallback: true

# Minimal Logging
logging:
  level:
    root: INFO
    com.translator: DEBUG
    org.springframework.boot.web: INFO
  pattern:
    console: "%d{HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"