server:
  port: ${PORT:8080}

spring:
  application:
    name: GlobalWeb Converter
  
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  
  thymeleaf:
    cache: false

# Translation Configuration
translation:
  provider: google
  mock-fallback: true

# Minimal Logging
logging:
  level:
    root: INFO
  pattern:
    console: "%d{HH:mm:ss} - %msg%n"